version: "3.3"

services:
  # server:
  #   container_name: todo-app-server
  #   build:
  #     context: .
  #     dockerfile: ./build/Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - .:/app
  #   depends_on: [db]

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  db-store:
